### ISSUE TITLE
Fix internal server error when clicking play button

### ISSUE THREAD

**Issue by stephanethomas** [protyposis/LocalAudioBroadcast#1]
I've updated to the 1.2 release and the following exception is raised whenever I click on the play button:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
OpenSource.UPnP.UPnPInvokeException:  Internal Server Error
   at OpenSource.UPnP.UPnPService.InvokeSync(String MethodName, UPnPArgument[] InVarArr)
   at LocalAudioBroadcast.ControlPoint.SetAVTransportURI()
   at LocalAudioBroadcast.MainForm.btnPlay_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Note the UPnP renderer is correctly detected. 1.1 release works perfectly fine for me.

**Comment by protyposis** [comment]
Thanks for reporting, I think I know what the problem is. Can you please tell me which UPnP renderer you're using so I can validate?

**Comment by stephanethomas** [comment]
Sure. [That one](http://europe.yamaha.com/en/products/audio-visual/hifi-components/stereo-receivers/r-n301_g/).

**Comment by protyposis** [comment]
Alright I was hoping for a software renderer ;) I just uploaded a new version, let me know if it works. If not, there's still two alternatives I can try.

**Comment by stephanethomas** [comment]
Unfortunately I still get an error with the new version:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
OpenSource.UPnP.UPnPInvokeException:  Internal Server Error
   at OpenSource.UPnP.UPnPService.InvokeSync(String MethodName, UPnPArgument[] InVarArr)
   at LocalAudioBroadcast.ControlPoint.SetAVTransportURI()
   at LocalAudioBroadcast.MainForm.btnPlay_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
LocalAudioBroadcast
    Assembly Version: 1.0.5546.20938
    Win32 Version: 1.0.*
    CodeBase: file:///D:/Install/install/Software/Multimedia/Local%20Audio%20Broadcast%201.2.1/LocalAudioBroadcast.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8008 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
UPnP
    Assembly Version: 1.0.5329.22108
    Win32 Version: 1.0.5329.22108
    CodeBase: file:///D:/Install/install/Software/Multimedia/Local%20Audio%20Broadcast%201.2.1/UPnP.DLL
----------------------------------------
HttpServer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Install/install/Software/Multimedia/Local%20Audio%20Broadcast%201.2.1/HttpServer.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
NAudio
    Assembly Version: 1.5.8.0
    Win32 Version: 1.5.8.0
    CodeBase: file:///D:/Install/install/Software/Multimedia/Local%20Audio%20Broadcast%201.2.1/NAudio.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8010 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_64/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by protyposis** [comment]
Here's the other two alternatives, please put them into the app folder and give them a try: http://www.mediafire.com/download/8l201gyrn3zti9g/LocalAudioBroadcast_TestFixes.zip

**Comment by stephanethomas** [comment]
`LocalAudioBroadcast_TestFix2.exe` did not raise any error and worked fine!

**Comment by protyposis** [comment]
Solved, thank you!
